#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if command -v google-chrome &> /dev/null; then
    google-chrome --app="file://$DIR/src/index.html" --user-data-dir="$HOME/.config/RayMusic" --window-size=1280,800
elif command -v chromium &> /dev/null; then
    chromium --app="file://$DIR/src/index.html" --user-data-dir="$HOME/.config/RayMusic" --window-size=1280,800
elif command -v chromium-browser &> /dev/null; then
    chromium-browser --app="file://$DIR/src/index.html" --user-data-dir="$HOME/.config/RayMusic" --window-size=1280,800
else
    xdg-open "$DIR/src/index.html"
fi
